# Generated by Django 5.0.2 on 2024-02-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('rua', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
